[package]
name = "minijinja-csharp"
version = "0.1.0"
edition = "2021"

[dependencies]
minijinja-cabi = { git = "https://github.com/mitsuhiko/minijinja.git" }
minijinja = { git = "https://github.com/mitsuhiko/minijinja.git" }

[lib]
crate-type = ["cdylib"]

[build-dependencies]
csbindgen = "1.9.5"
